Implement comments for maps and collections with snakeyaml
OkaeriPoland/okaeri-configs pull request #34
Opened 2022-08-05 20:44 UTC by Brikster

Fix issue #17.

Rewritten `ConfigPostprocessor` to provide first line of collection to a walker (previously, lines that begins from "-" were written as is). `YamlSectionWalker`'s implementations now resolve subtypes of Map and Collection and append comments of their fields.

Now there is an ability to create commented Lists, Maps, Lists of Maps, Maps of Lists etc.

Here you can see an example:
```
import eu.okaeri.configs.OkaeriConfig;
import eu.okaeri.configs.annotation.*;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;

import java.util.*;

@Getter
@SuppressWarnings("FieldMayBeFinal")
@Names(strategy = NameStrategy.HYPHEN_CASE, modifier = NameModifier.TO_LOWER_CASE)
public class ExampleConfig extends OkaeriConfig {

    @Exclude
    private static final ExampleSubConfig anotherExampleSubConfigValue = new ExampleSubConfig("Custom awesome value", 2022);

    @Comment
    private List<ExampleSubConfig> subConfigsList = Arrays.asList(new ExampleSubConfig(), anotherExampleSubConfigValue);

    @Comment
    private Map<String, ExampleSubConfig> subConfigsMap = new HashMap<String, ExampleSubConfig>() {{
        put("first-map-key", new ExampleSubConfig());
        put("second-map-key", anotherExampleSubConfigValue);
    }};

    @Comment
    private List<Map<String, ExampleSubConfig>> subConfigsMapsList = Collections.singletonList(new HashMap<String, ExampleSubConfig>() {{
        put("first-map-key", new ExampleSubConfig());
        put("second-map-key", anotherExampleSubConfigValue);
    }});

    @Comment
    private Map<String, List<ExampleSubConfig>> subConfigsListsMap = new HashMap<String, List<ExampleSubConfig>>() {{
        put("first-map-key", Arrays.asList(new ExampleSubConfig(), anotherExampleSubConfigValue));
        put("second-map-key", Arrays.asList(new ExampleSubConfig(), anotherExampleSubConfigValue));
    }};

    @Getter
    @SuppressWarnings("FieldMayBeFinal")
    @AllArgsConstructor
    @NoArgsConstructor
    @Names(strategy = NameStrategy.HYPHEN_CASE, modifier = NameModifier.TO_LOWER_CASE)
    public static class ExampleSubConfig extends OkaeriConfig {

        @Comment("You can see this comment inside maps and collections")
        private String someKeyFirst = "Awesome value";

        @Comment("And this comment too")
        private int someKeySecond = 1337;

    }

}
```

And config file:
```
sub-configs-list:
- # You can see this comment inside maps and collections
  some-key-first: Awesome value
  # And this comment too
  some-key-second: 1337
- # You can see this comment inside maps and collections
  some-key-first: Custom awesome value
  # And this comment too
  some-key-second: 2022

sub-configs-map:
  second-map-key:
    # You can see this comment inside maps and collections
    some-key-first: Custom awesome value
    # And this comment too
    some-key-second: 2022
  first-map-key:
    # You can see this comment inside maps and collections
    some-key-first: Awesome value
    # And this comment too
    some-key-second: 1337

sub-configs-maps-list:
- second-map-key:
    # You can see this comment inside maps and collections
    some-key-first: Custom awesome value
    # And this comment too
    some-key-second: 2022
  first-map-key:
    # You can see this comment inside maps and collections
    some-key-first: Awesome value
    # And this comment too
    some-key-second: 1337

sub-configs-lists-map:
  second-map-key:
  - # You can see this comment inside maps and collections
    some-key-first: Awesome value
    # And this comment too
    some-key-second: 1337
  - # You can see this comment inside maps and collections
    some-key-first: Custom awesome value
    # And this comment too
    some-key-second: 2022
  first-map-key:
  - # You can see this comment inside maps and collections
    some-key-first: Awesome value
    # And this comment too
    some-key-second: 1337
  - # You can see this comment inside maps and collections
    some-key-first: Custom awesome value
    # And this comment too
    some-key-second: 2022

```

2022-08-05 21:27 UTC, PinkLolicorn requested changes

2022-08-05 21:27 UTC, PinkLolicorn commented on core/pom.xml
> -        <version>4.0.6</version>
No project version bumps please

2022-08-05 21:27 UTC, PinkLolicorn commented on core/src/main/java/eu/okaeri/configs/postprocessor/ConfigPostprocessor.java
> +            while (collectionsStartCount != 0) {
The logic changes in this class are really convoluted and have a lot of mutation based whiles. This needs better structure, should be very much doable with at least semi-simple result.

2022-08-05 21:30 UTC, PinkLolicorn commented
Including comments in each map/collection element is messy and confusing for the end user. It should be only in the first one.

2023-06-19 13:12 UTC, P3ridot commented
> Including comments in each map/collection element is messy and confusing for the end user. It should be only in the first one.

Would be better, if it would be configurable

2025-04-29 15:52 UTC, closed without merging